name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: boschcrank/oss-review-toolkit@master
      with:
        ort-args: 'analyze -i . -o ort-results'
