name: CI

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2-beta
      with:
        ref: 'master'
        path: 'master'
    - uses: actions/checkout@v2-beta
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        path: 'pr'
    - run: cd ..
    - uses: boschcrank/oss-review-toolkit@master
      with:
        input-dir: '/github/workspace/master'
        output-dir: '/github/workspace/master/results'
    - uses: boschcrank/oss-review-toolkit@master
      with:
        input-dir: '/github/workspace/pr'
        output-dir: '/github/workspace/pr/results'
    - run: cat results-master/analyzer-result.json
    - run: cat results-pr/analyzer-result.json
