name: CI

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: 'master'
    - uses: boschcrank/oss-review-toolkit@master
      with:
        output-dir: '/github/workspace/results-master'
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: boschcrank/oss-review-toolkit@master
      with:
        output-dir: '/github/workspace/results-pr'
    - run: cat results-master/analyzer-result.json
    - run: cat results-pr/analyzer-result.json
